name: App workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test-client:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm ci
          npx ng test --browsers=ChromeHeadless
      - name: Run tests
        run: npm test
  test-server:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install browsers and OS dependencies
        run: playwright install --with-deps chromium
      - name: Launch app
        run: |
          fastapi dev src/main.py &

          for i in {1..10}; do
            curl -s http://localhost:8000/healthcheck && break
            echo "Waiting for API to be ready..."
            sleep 3
          done

          if ! curl -s http://localhost:8000/healthcheck; then
            echo "API is not ready after waiting for 30 seconds."
            exit 1
          fi
      - name: Run tests
        run: pytest --browser chromium --tracing=retain-on-failure
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
